import type { TrainingResource } from '../types';

export const TRAINING_RESOURCES: TrainingResource[] = [
  // ─── Health Sharing Introduction & Processes ─────────────────────────
  {
    id: 'how-healthshare-works',
    title: 'How Our Healthshare Works',
    description: 'Overview of how the health sharing model operates across our partner networks',
    url: 'https://mpb.health/how-it-works',
    category: 'health-sharing',
    type: 'document',
    external: true,
    links: [
      { label: 'MPB Health', url: 'https://mpb.health/how-it-works' },
      { label: 'Zion HealthShare', url: 'https://zionhealthshare.org/how-it-works/' },
      { label: 'Sedera', url: 'https://sedera.com/' },
    ],
    keywords: ['sharing request', 'IUA', 'initial unshareable amount', 'monthly share', 'pre-existing condition', 'eligible expenses', 'community', 'cost sharing', 'not insurance', 'membership', 'enrollment', 'network', 'provider'],
  },
  {
    id: 'member-guidelines',
    title: 'Member Guidelines',
    description: 'Health sharing member guidelines and policies',
    url: 'https://zionhealthshare.org/how-it-works/member-guidelines/',
    category: 'health-sharing',
    type: 'document',
    external: true,
    links: [
      { label: 'Zion HealthShare', url: 'https://zionhealthshare.org/how-it-works/member-guidelines/' },
      { label: 'Sedera', url: 'https://assets.ctfassets.net/01zqqfy0bb2m/BdCi3f2zO5AcFTHBLcNkJ/3cdf28f268d4186cc7550e11b11664c7/SELECT__Guidelines_-_Community_20231001.pdf' },
      {
        label: 'Zion vs Sedera',
        url: 'https://netorg6712533-my.sharepoint.com/:x:/g/personal/julia_mympb_com/IQD4GvNM8LwXQKzAX6zyyT-jAdAVEGVRvYXfohBdzTCvAyY?rtime=ye2RGwim3kg',
      },
    ],
    keywords: [
      'eligibility',
      'waiting period',
      'pre-existing',
      'pre-notification',
      'maternity',
      'mental health',
      'substance abuse',
      'tobacco',
      'lifestyle',
      'exclusions',
      'limitations',
      'appeal',
      'needs processing',
      'Zion vs Sedera',
      'comparison',
      'guidelines comparison',
      'Sedera',
    ],
  },
  {
    id: 'proof-of-sharing-savvos-sedera',
    title: 'Proof of Sharing Letter',
    description: 'Opens in SharePoint (Word on the web).',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/IQDqN0fINTBARb2qH6OKUFAUAQQ6k_iUpFbwa8P7ZOr0s-M?e=k6epW6',
    category: 'health-sharing',
    type: 'document',
    external: true,
    links: [
      {
        label: 'Open proof of sharing letter',
        url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/IQDqN0fINTBARb2qH6OKUFAUAQQ6k_iUpFbwa8P7ZOr0s-M?e=k6epW6',
      },
    ],
    keywords: [
      'proof of sharing',
      'proof of sharing letter',
      'letter',
      'SAVVOS',
      'Savvos',
      'Sedera',
      'sharing',
      'verification',
      'documentation',
    ],
  },
  {
    id: 'mcs-resources',
    title: 'MCS Resources',
    description:
      'Member care systems quick links: Zion HealthShare FAQ and SAVVOS Health / Sedera reference (PDF).',
    url: 'https://zionhealthshare.org/how-it-works/faq/',
    category: 'health-sharing',
    type: 'document',
    external: true,
    links: [
      { label: 'Zion HealthShare FAQ', url: 'https://zionhealthshare.org/how-it-works/faq/' },
      {
        label: 'SAVVOS Health & Sedera (PDF)',
        url: '/docs/SAVVOS%20Health%20(1).pdf',
      },
    ],
    keywords: [
      'MCS',
      'member care systems',
      'Zion FAQ',
      'Zion Health FAQ',
      'frequently asked questions',
      'how does it work',
      'who is eligible',
      'cancel',
      'refund',
      'what is covered',
      'emergency',
      'urgent care',
      'prescription',
      'dental',
      'vision',
      'pre-existing',
      'Sedera',
      'Savvos',
      'SAVVOS',
    ],
  },
  {
    id: 'terminology-and-medical-hsa',
    title: 'Healthshare terminology & Medical expenses / HSA',
    description:
      'Health sharing terms and definitions, plus medical expenses and Health Savings Account guidance (two PDFs).',
    url: 'https://netorg6712533-my.sharepoint.com/:b:/g/personal/ali_mympb_com/EY8tLxOwrgFIpfQ1MSrnapgBkc-iH-7AaFf24q88CB-6Fg?e=GDaW15',
    category: 'health-sharing',
    type: 'pdf',
    external: true,
    links: [
      {
        label: 'Health Share Terminology',
        url: 'https://netorg6712533-my.sharepoint.com/:b:/g/personal/ali_mympb_com/EY8tLxOwrgFIpfQ1MSrnapgBkc-iH-7AaFf24q88CB-6Fg?e=GDaW15',
      },
      {
        label: 'Medical Expenses and HSA',
        url: 'https://netorg6712533-my.sharepoint.com/:b:/g/personal/julia_mympb_com/ERuAuA74FqZDkPeq5VZ5uPUB45UMEuRkKfzlTtCb-n2_FQ?e=sK85Ag',
      },
    ],
    keywords: [
      'terminology',
      'definitions',
      'IUA',
      'initial unshareable amount',
      'sharing request',
      'monthly share',
      'pre-notification',
      'eligible expense',
      'eligible expenses',
      'EOB',
      'explanation of benefits',
      'copay',
      'deductible',
      'coinsurance',
      'out of pocket',
      'maximum',
      'PPO',
      'HMO',
      'network',
      'HSA',
      'health savings account',
      'tax deductible',
      'qualified medical expense',
      'IRS',
      'contribution limits',
      'HDHP',
      'high deductible',
      'triple tax advantage',
      'rollover',
      'savings',
    ],
  },
  {
    id: 'healthshare-sop',
    title: 'Health Sharing SOPs',
    description: 'Standard operating procedures for concierge healthshare processes',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/Ec9NzRCJwDRPnpgIr0WuF9ABlqNSEnxHA3Fvw0UANjF_wA',
    category: 'health-sharing',
    type: 'sop',
    external: true,
    keywords: ['sharing request', 'pre-notification', 'submit', 'claims', 'member call', 'escalation', 'provider call', 'billing', 'EOB', 'repricing', 'PHCS', 'network discount', 'needs processing', 'step by step'],
  },

  // ─── MPB Plans: Member Handbooks ─────────────────────────────────────
  {
    id: 'membership-comparison-chart',
    title: 'Membership Comparison Chart',
    description: 'Side-by-side comparison of all MPB plan types',
    url: 'https://netorg6712533-my.sharepoint.com/:b:/g/personal/julia_mympb_com/ESb2dGtgwZVOgREY0vtMrG8BB28yeFirhtdaCL-Jqo-AFw?e=ibWNya',
    category: 'mpb-plans',
    type: 'pdf',
    external: true,
    keywords: ['essentials', 'care plus', 'secure HSA', 'direct', 'MEC', 'comparison', 'pricing', 'benefits', 'IUA', 'monthly cost', 'telehealth', 'copay', 'preventive', 'maternity', 'mental health'],
  },
  {
    id: 'essentials-handbook',
    title: 'Essentials Handbook',
    description: 'Complete handbook for the Essentials plan',
    url: 'https://mpb.health/3d-flip-book/essentials/',
    category: 'mpb-plans',
    subcategory: 'Essentials',
    type: 'handbook',
    external: true,
    keywords: ['Zion', 'IUA', 'sharing request', 'eligible expenses', 'network', 'PHCS', 'pre-notification', 'emergency', 'urgent care', 'prescription', 'telehealth', 'preventive', 'wellness'],
  },
  {
    id: 'mec-essentials-handbook',
    title: 'MEC + Essentials Handbook',
    description: 'Complete handbook for the MEC + Essentials plan',
    url: 'https://mpb.health/3d-flip-book/mecessentials-handbook/',
    category: 'mpb-plans',
    subcategory: 'MEC + Essentials',
    type: 'handbook',
    external: true,
    keywords: ['minimum essential coverage', 'ACA', 'Affordable Care Act', 'Zion', 'ARM', 'telehealth', 'IUA', 'sharing request', 'preventive', 'wellness', 'copay', 'network', 'PHCS'],
  },
  {
    id: 'care-plus-handbook',
    title: 'Care Plus Handbook',
    description: 'Complete handbook for the Care Plus plan',
    url: 'https://mpb.health/3d-flip-book/careplus/',
    category: 'mpb-plans',
    subcategory: 'Care Plus',
    type: 'handbook',
    external: true,
    keywords: ['Zion', 'Sedera', 'IUA', 'sharing request', 'maternity', 'mental health', 'prescription', 'network', 'PHCS', 'preventive', 'emergency', 'specialist', 'copay'],
  },
  {
    id: 'secure-hsa-handbook',
    title: 'Secure HSA Handbook',
    description: 'Complete handbook for the Secure HSA plan',
    url: 'https://mpb.health/3d-flip-book/secure-hsa/',
    category: 'mpb-plans',
    subcategory: 'Secure HSA',
    type: 'handbook',
    external: true,
    keywords: ['HSA', 'health savings account', 'high deductible', 'HDHP', 'tax advantage', 'Zion', 'Sedera', 'IUA', 'sharing request', 'eligible expenses', 'network', 'PHCS', 'preventive'],
  },
  {
    id: 'direct-handbook',
    title: 'Direct Handbook',
    description: 'Complete handbook for the Direct plan',
    url: 'https://mpb.health/3d-flip-book/direct/',
    category: 'mpb-plans',
    subcategory: 'Direct',
    type: 'handbook',
    external: true,
    keywords: ['Sedera', 'direct primary care', 'DPC', 'sharing request', 'IUA', 'community', 'eligible expenses', 'network', 'PHCS', 'preventive', 'telehealth'],
  },

  // ─── Welcome Call Scripts ────────────────────────────────────────────
  {
    id: 'essentials-welcome-call',
    title: 'Essentials Welcome Call',
    description: 'Welcome call script for Essentials plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/IQBzKuBNbNxUQLqUQYkqNJm7AY9HkeLRS3SUZCFZ_IRQB5Y?e=USndq3',
    category: 'welcome-scripts',
    subcategory: 'Essentials',
    type: 'script',
    external: true,
    keywords: ['onboarding', 'new member', 'introduction', 'benefits overview', 'ID card', 'telehealth', 'portal login', 'concierge number', 'Zion', 'PHCS', 'welcome'],
  },
  {
    id: 'mec-essentials-welcome-call',
    title: 'MEC Essentials Welcome Call Script',
    description: 'Welcome call script for MEC + Essentials plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EYAh_A1p-FxAvkiQtEqEWxAB_plNoZ5cVdbj7vJb7zq-wA',
    category: 'welcome-scripts',
    subcategory: 'MEC + Essentials',
    type: 'script',
    external: true,
    keywords: ['onboarding', 'new member', 'MEC', 'ARM', 'minimum essential coverage', 'ACA', 'telehealth', 'ID card', 'portal', 'concierge', 'Zion', 'welcome'],
  },
  {
    id: 'care-plus-welcome-call',
    title: 'Care Plus Welcome Call',
    description: 'Welcome call script for Care Plus plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/ETJv4LD3egxJkQozcevpa5UBXWjtLnysdSxIOpMRUHx5Dw',
    category: 'welcome-scripts',
    subcategory: 'Care Plus',
    type: 'script',
    external: true,
    keywords: ['onboarding', 'new member', 'benefits overview', 'ID card', 'telehealth', 'portal', 'concierge', 'Zion', 'Sedera', 'PHCS', 'maternity', 'mental health', 'welcome'],
  },
  {
    id: 'secure-hsa-welcome-call',
    title: 'Secure HSA Welcome Call Script',
    description: 'Welcome call script for Secure HSA plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EQPUyBqxElBPr5TI7Xf23-cBplWCFec1ai8Rvcoi6rfqkg',
    category: 'welcome-scripts',
    subcategory: 'Secure HSA',
    type: 'script',
    external: true,
    keywords: ['onboarding', 'new member', 'HSA', 'health savings account', 'HDHP', 'tax advantage', 'benefits overview', 'ID card', 'telehealth', 'portal', 'concierge', 'welcome'],
  },
  {
    id: 'direct-welcome-call',
    title: 'Direct Welcome Call Script',
    description: 'Welcome call script for Direct plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EdoEubsU3-ZLtcYwxU8_vCMBEwGjCd3KPqoLm3rZPvcpoA',
    category: 'welcome-scripts',
    subcategory: 'Direct',
    type: 'script',
    external: true,
    keywords: ['onboarding', 'new member', 'direct primary care', 'DPC', 'Sedera', 'benefits overview', 'ID card', 'telehealth', 'portal', 'concierge', 'welcome'],
  },
  {
    id: 'premium-care-welcome-call',
    title: 'Premium Care Welcome Call',
    description: 'Welcome call script for Premium Care plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/IQAqM1whJWEwRIEoXKV0yk9jAY_LhhbgaTL5M_LAwi8MIDk?e=1yED8K',
    category: 'welcome-scripts',
    subcategory: 'Premium Care',
    type: 'script',
    external: true,
    keywords: [
      'onboarding',
      'new member',
      'Premium Care',
      'benefits overview',
      'ID card',
      'telehealth',
      'portal',
      'concierge',
      'welcome',
      'SharePoint',
    ],
  },
  {
    id: 'premium-hsa-welcome-call',
    title: 'Premium HSA Welcome Call',
    description: 'Welcome call script for Premium HSA plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/IQDYC0JTBAPjTLzEdfIjmiSoAcHT3W0NAkUguemQnd9_-Kg?e=JTG7Zs',
    category: 'welcome-scripts',
    subcategory: 'Premium HSA',
    type: 'script',
    external: true,
    keywords: [
      'onboarding',
      'new member',
      'Premium HSA',
      'HSA',
      'health savings account',
      'benefits overview',
      'ID card',
      'telehealth',
      'portal',
      'concierge',
      'welcome',
      'SharePoint',
    ],
  },

  // ─── Telehealth & MEC ───────────────────────────────────────────────
  {
    id: 'arm-sop',
    title: 'ARM SOP',
    description: 'Standard operating procedures for ARM telehealth services',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EV08fw4Mge1BmqRj2MG3bsIBNgN1yh783WdIK0rJ3Qnevg',
    category: 'telehealth',
    type: 'sop',
    external: true,
    keywords: ['ARM', 'MEC', 'minimum essential coverage', 'telehealth visit', 'virtual doctor', 'copay', 'ID card', 'eligibility', 'activation', 'enrollment', 'portal', 'mediconnx'],
  },
  {
    id: 'arm-hdhp-sbc-2026',
    title: 'ARM HDHP Plan SBC 2026',
    description: 'Summary of Benefits and Coverage for the ARM High Deductible Health Plan (2026)',
    url: '#',
    category: 'telehealth',
    subcategory: 'ARM',
    type: 'pdf',
    external: true,
    keywords: ['SBC', 'summary of benefits', 'HDHP', 'high deductible', 'deductible', 'out of pocket maximum', 'copay', 'coinsurance', 'preventive', 'emergency', 'hospitalization', 'prescription', 'specialist', '2026'],
  },
  {
    id: 'arm-proof-of-coverage',
    title: 'ARM Proof of Coverage Letter',
    description: 'Opens in SharePoint.',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/IQAT4JP_jaafQKejx8ZJRsS5AX1mJaLP3gcQH3wnJpaYn5s?e=aDgCeJ',
    category: 'telehealth',
    subcategory: 'ARM',
    type: 'document',
    external: true,
    links: [
      {
        label: 'Open proof of coverage letter',
        url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/IQAT4JP_jaafQKejx8ZJRsS5AX1mJaLP3gcQH3wnJpaYn5s?e=aDgCeJ',
      },
    ],
    keywords: [
      'proof of coverage',
      'verification',
      'insurance verification',
      'coverage letter',
      'certificate of coverage',
      'eligibility',
      'member ID',
      'effective date',
      'employer',
      'group number',
      'ARM',
      'MEC',
      'HDHP',
      'MediConnx',
      'Word',
      'SharePoint',
    ],
  },
  {
    id: 'arm-welcome-letter-2026',
    title: 'ARM Welcome Letter 2026',
    description: 'Welcome letter for new ARM plan members (2026)',
    url: '#',
    category: 'telehealth',
    subcategory: 'ARM',
    type: 'pdf',
    external: true,
    keywords: ['welcome', 'new member', 'enrollment', 'ID card', 'portal access', 'telehealth', 'benefits', 'effective date', '2026'],
  },
  {
    id: 'mpb-telehealth-sop',
    title: 'MPB Telehealth',
    description: 'Standard operating procedures for Lyric telehealth services',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/IQB3dzaWvLFLTb2H4TDBD32pAS1YD0NP8EscdVq1tL716uQ?e=cLLmyD',
    category: 'telehealth',
    type: 'sop',
    external: true,
    keywords: ['Lyric', 'telehealth', 'virtual visit', 'video call', 'doctor', 'copay', 'activation', 'registration', 'portal', 'app', 'urgent care', 'prescription', 'mental health', 'behavioral health'],
  },

  // ─── Internal Daily SOPs ────────────────────────────────────────────
  {
    id: 'daily-concierge-checklist',
    title: 'Daily Mandatory Concierge Checklist',
    description: 'Daily checklist that must be completed by all concierge staff',
    url: 'https://teams.microsoft.com/l/entity/d7958adf-f419-46fa-941b-1b946497ef84/_djb2_msteams_prefix_2637388461?context=%7B%22chatId%22%3A%2219%3Aa9d9ce57ca0d4e05859608b503bca9d1%40thread.v2%22%2C%22contextType%22%3A%22chat%22%7D&tenantId=ad4e49c8-3dea-4d37-8be6-ee2fdc324f04',
    category: 'internal-sops',
    type: 'checklist',
    external: true,
    keywords: ['daily tasks', 'morning', 'Teams', 'voicemail', 'email', 'follow up', 'Zoho', 'queue', 'clock in', 'clock out', 'end of day', 'mandatory', 'attendance'],
  },
  {
    id: 'tasks-follow-up-sop',
    title: 'Tasks and Follow Up Process SOP',
    description: 'Procedures for managing tasks and follow-ups with members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EWUTlCt1vZRJiC7OE7mkXkYBiuxuBDS4s7sCF865wtV7YA',
    category: 'internal-sops',
    type: 'sop',
    external: true,
    keywords: ['task management', 'follow up', 'callback', 'member outreach', 'Zoho', 'CRM', 'notes', 'status update', 'pending', 'overdue', 'priority', 'scheduling'],
  },
  {
    id: 'healthcare-blue-book-sop',
    title: 'Healthcare Blue Book SOP',
    description: 'How to use the Healthcare Blue Book for pricing research',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EZWFcVAHVQNJuABKiikvoucBMh42K8kbZ07a4oRguTX3yw',
    category: 'internal-sops',
    type: 'sop',
    external: true,
    keywords: ['fair price', 'cost estimate', 'procedure cost', 'surgery cost', 'pricing', 'negotiation', 'Valenz', 'blue book', 'CPT code', 'provider search', 'cost comparison', 'out of pocket'],
  },
  {
    id: 'rx-labs-sop',
    title: 'RX and Labs SOP',
    description: 'Procedures for prescriptions and lab work coordination',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EdGllDdmZJ9OqgzZ8lw05LABcUvpRbats4kPQyp7RxP2bg',
    category: 'internal-sops',
    type: 'sop',
    external: true,
    keywords: ['prescription', 'medication', 'pharmacy', 'GoodRx', 'RxGo', 'discount card', 'lab work', 'blood test', 'CBC', 'CMP', 'lipid panel', 'lab order', 'LabCorp', 'Quest', 'LaboratoryAssist', 'Canadian drug store', 'Cost Plus'],
  },
  {
    id: 'imaging-search-sop',
    title: 'Imaging Search SOP',
    description: 'How to search for and coordinate imaging services for members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/ESDYLkU_FplOljNVG8oLhzQBApb4ZCxN4SPbj0jsnfh7OA',
    category: 'internal-sops',
    type: 'sop',
    external: true,
    keywords: ['MRI', 'CT scan', 'X-ray', 'ultrasound', 'mammogram', 'PET scan', 'RadiologyAssist', 'imaging center', 'scheduling', 'referral', 'authorization', 'cost estimate', 'cash pay', 'radiology'],
  },
  {
    id: 'appointment-setting-sop',
    title: 'Appointment Setting SOP',
    description: 'Procedures for setting appointments on behalf of members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EW6RPk9jIJVOjH53SHbMzYcBAaPYxMsUW6VW5tRlyZDmyQ',
    category: 'internal-sops',
    type: 'sop',
    external: true,
    keywords: ['appointment', 'scheduling', 'provider', 'specialist', 'referral', 'PCP', 'primary care', 'ZocDoc', 'PHCS', 'network', 'in-network', 'out-of-network', 'authorization', 'three-way call'],
  },

  // ─── Customer Service ────────────────────────────────────────────────
  {
    id: 'member-deescalation',
    title: 'Member De-escalation',
    description: 'How to handle difficult members and de-escalate situations',
    url: 'https://netorg6712533.sharepoint.com/:w:/s/ConciergeTraining900/EZmTc_IDN6lLhnSFMOVZfBoBu7WPDnfo5s_xlp8FGD06Pw?e=WCfrdo',
    category: 'customer-service',
    type: 'document',
    external: true,
    keywords: ['angry member', 'frustrated', 'complaint', 'de-escalate', 'calm down', 'empathy', 'active listening', 'apologize', 'resolution', 'supervisor', 'escalation', 'refund', 'cancellation', 'conflict', 'difficult conversation'],
  },
  {
    id: 'customer-service-101',
    title: 'Customer Service 101',
    description: 'Foundational customer service training for concierge staff',
    url: 'https://netorg6712533.sharepoint.com/:w:/s/ConciergeTraining900/EaselpITM_5FsOC3TugMl_0BsAIBHJ1risN7y7mZKsDbQg?e=Rpbhaz',
    category: 'customer-service',
    type: 'document',
    external: true,
    keywords: ['greeting', 'phone etiquette', 'hold', 'transfer', 'tone of voice', 'professionalism', 'empathy', 'active listening', 'first call resolution', 'follow up', 'member satisfaction', 'communication skills', 'rapport'],
  },
];
