import type { TrainingResource } from '../types';

export const TRAINING_RESOURCES: TrainingResource[] = [
  // ─── Health Sharing Introduction & Processes ─────────────────────────
  {
    id: 'how-healthshare-works',
    title: 'How Our Healthshare Works',
    description: 'Overview of how the Zion HealthShare model operates',
    url: 'https://zionhealthshare.org/how-it-works/',
    category: 'health-sharing',
    type: 'document',
    external: true,
  },
  {
    id: 'zion-member-guidelines',
    title: 'Member Guidelines',
    description: 'Zion HealthShare member guidelines and policies',
    url: 'https://zionhealthshare.org/how-it-works/member-guidelines/',
    category: 'health-sharing',
    type: 'document',
    external: true,
  },
  {
    id: 'zion-faq',
    title: 'Zion Health FAQ',
    description: 'Frequently asked questions about Zion HealthShare',
    url: 'https://zionhealthshare.org/how-it-works/faq/',
    category: 'health-sharing',
    type: 'document',
    external: true,
  },
  {
    id: 'terminology-sheet',
    title: 'Health Share Terminology',
    description: 'Key terms and definitions used in health sharing',
    url: 'https://netorg6712533-my.sharepoint.com/:b:/g/personal/ali_mympb_com/EY8tLxOwrgFIpfQ1MSrnapgBkc-iH-7AaFf24q88CB-6Fg?e=GDaW15',
    category: 'health-sharing',
    type: 'pdf',
    external: true,
  },
  {
    id: 'medical-expenses-hsa',
    title: 'Medical Expenses and HSA',
    description: 'Guide to medical expenses and Health Savings Accounts',
    url: 'https://netorg6712533-my.sharepoint.com/:b:/g/personal/julia_mympb_com/ERuAuA74FqZDkPeq5VZ5uPUB45UMEuRkKfzlTtCb-n2_FQ?e=sK85Ag',
    category: 'health-sharing',
    type: 'pdf',
    external: true,
  },
  {
    id: 'healthshare-sop',
    title: 'Health Sharing SOPs',
    description: 'Standard operating procedures for concierge healthshare processes',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/Ec9NzRCJwDRPnpgIr0WuF9ABlqNSEnxHA3Fvw0UANjF_wA',
    category: 'health-sharing',
    type: 'sop',
    external: true,
  },
  {
    id: 'member-deescalation',
    title: 'Member De-escalation',
    description: 'How to handle difficult members and de-escalate situations',
    url: 'https://netorg6712533.sharepoint.com/:w:/s/ConciergeTraining900/EZmTc_IDN6lLhnSFMOVZfBoBu7WPDnfo5s_xlp8FGD06Pw?e=WCfrdo',
    category: 'health-sharing',
    type: 'document',
    external: true,
  },
  {
    id: 'customer-service-101',
    title: 'Customer Service 101',
    description: 'Foundational customer service training for concierge staff',
    url: 'https://netorg6712533.sharepoint.com/:w:/s/ConciergeTraining900/EaselpITM_5FsOC3TugMl_0BsAIBHJ1risN7y7mZKsDbQg?e=Rpbhaz',
    category: 'health-sharing',
    type: 'document',
    external: true,
  },

  // ─── MPB Plans: Member Handbooks ─────────────────────────────────────
  {
    id: 'membership-comparison-chart',
    title: 'Membership Comparison Chart',
    description: 'Side-by-side comparison of all MPB plan types',
    url: 'https://netorg6712533-my.sharepoint.com/:b:/g/personal/julia_mympb_com/ESb2dGtgwZVOgREY0vtMrG8BB28yeFirhtdaCL-Jqo-AFw?e=ibWNya',
    category: 'mpb-plans',
    type: 'pdf',
    external: true,
  },
  {
    id: 'essentials-handbook',
    title: 'Essentials Handbook',
    description: 'Complete handbook for the Essentials plan',
    url: 'https://mpb.health/3d-flip-book/essentials/',
    category: 'mpb-plans',
    subcategory: 'Essentials',
    type: 'handbook',
    external: true,
  },
  {
    id: 'mec-essentials-handbook',
    title: 'MEC + Essentials Handbook',
    description: 'Complete handbook for the MEC + Essentials plan',
    url: 'https://mpb.health/3d-flip-book/mecessentials-handbook/',
    category: 'mpb-plans',
    subcategory: 'MEC + Essentials',
    type: 'handbook',
    external: true,
  },
  {
    id: 'care-plus-handbook',
    title: 'Care Plus Handbook',
    description: 'Complete handbook for the Care Plus plan',
    url: 'https://mpb.health/3d-flip-book/careplus/',
    category: 'mpb-plans',
    subcategory: 'Care Plus',
    type: 'handbook',
    external: true,
  },
  {
    id: 'secure-hsa-handbook',
    title: 'Secure HSA Handbook',
    description: 'Complete handbook for the Secure HSA plan',
    url: 'https://mpb.health/3d-flip-book/secure-hsa/',
    category: 'mpb-plans',
    subcategory: 'Secure HSA',
    type: 'handbook',
    external: true,
  },
  {
    id: 'direct-handbook',
    title: 'Direct Handbook',
    description: 'Complete handbook for the Direct plan',
    url: 'https://mpb.health/3d-flip-book/direct/',
    category: 'mpb-plans',
    subcategory: 'Direct',
    type: 'handbook',
    external: true,
  },

  // ─── Welcome Call Scripts ────────────────────────────────────────────
  {
    id: 'essentials-welcome-call',
    title: 'Essentials Welcome Call',
    description: 'Welcome call script for Essentials plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/ERPNv_Q6e0RElpA8ijlGZ8QBao0iKGiyuLoH7kcH8cQekQ',
    category: 'welcome-scripts',
    subcategory: 'Essentials',
    type: 'script',
    external: true,
  },
  {
    id: 'mec-essentials-welcome-call',
    title: 'MEC Essentials Welcome Call Script',
    description: 'Welcome call script for MEC + Essentials plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EYAh_A1p-FxAvkiQtEqEWxAB_plNoZ5cVdbj7vJb7zq-wA',
    category: 'welcome-scripts',
    subcategory: 'MEC + Essentials',
    type: 'script',
    external: true,
  },
  {
    id: 'care-plus-welcome-call',
    title: 'Care Plus Welcome Call',
    description: 'Welcome call script for Care Plus plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/ETJv4LD3egxJkQozcevpa5UBXWjtLnysdSxIOpMRUHx5Dw',
    category: 'welcome-scripts',
    subcategory: 'Care Plus',
    type: 'script',
    external: true,
  },
  {
    id: 'secure-hsa-welcome-call',
    title: 'Secure HSA Welcome Call Script',
    description: 'Welcome call script for Secure HSA plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EQPUyBqxElBPr5TI7Xf23-cBplWCFec1ai8Rvcoi6rfqkg',
    category: 'welcome-scripts',
    subcategory: 'Secure HSA',
    type: 'script',
    external: true,
  },
  {
    id: 'direct-welcome-call',
    title: 'Direct Welcome Call Script',
    description: 'Welcome call script for Direct plan members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EdoEubsU3-ZLtcYwxU8_vCMBEwGjCd3KPqoLm3rZPvcpoA',
    category: 'welcome-scripts',
    subcategory: 'Direct',
    type: 'script',
    external: true,
  },

  // ─── Telehealth & MEC ───────────────────────────────────────────────
  {
    id: 'arm-lyric-sop',
    title: 'ARM and Lyric SOP',
    description: 'Standard operating procedures for ARM and Lyric telehealth services',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EV08fw4Mge1BmqRj2MG3bsIBNgN1yh783WdIK0rJ3Qnevg',
    category: 'telehealth',
    type: 'sop',
    external: true,
  },

  // ─── Internal Daily SOPs ────────────────────────────────────────────
  {
    id: 'daily-concierge-checklist',
    title: 'Daily Mandatory Concierge Checklist',
    description: 'Daily checklist that must be completed by all concierge staff',
    url: 'https://teams.microsoft.com/l/entity/d7958adf-f419-46fa-941b-1b946497ef84/_djb2_msteams_prefix_2637388461?context=%7B%22chatId%22%3A%2219%3Aa9d9ce57ca0d4e05859608b503bca9d1%40thread.v2%22%2C%22contextType%22%3A%22chat%22%7D&tenantId=ad4e49c8-3dea-4d37-8be6-ee2fdc324f04',
    category: 'internal-sops',
    type: 'checklist',
    external: true,
  },
  {
    id: 'tasks-follow-up-sop',
    title: 'Tasks and Follow Up Process SOP',
    description: 'Procedures for managing tasks and follow-ups with members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EWUTlCt1vZRJiC7OE7mkXkYBiuxuBDS4s7sCF865wtV7YA',
    category: 'internal-sops',
    type: 'sop',
    external: true,
  },
  {
    id: 'healthcare-blue-book-sop',
    title: 'Healthcare Blue Book SOP',
    description: 'How to use the Healthcare Blue Book for pricing research',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EZWFcVAHVQNJuABKiikvoucBMh42K8kbZ07a4oRguTX3yw',
    category: 'internal-sops',
    type: 'sop',
    external: true,
  },
  {
    id: 'rx-labs-sop',
    title: 'RX and Labs SOP',
    description: 'Procedures for prescriptions and lab work coordination',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EdGllDdmZJ9OqgzZ8lw05LABcUvpRbats4kPQyp7RxP2bg',
    category: 'internal-sops',
    type: 'sop',
    external: true,
  },
  {
    id: 'imaging-search-sop',
    title: 'Imaging Search SOP',
    description: 'How to search for and coordinate imaging services for members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/ESDYLkU_FplOljNVG8oLhzQBApb4ZCxN4SPbj0jsnfh7OA',
    category: 'internal-sops',
    type: 'sop',
    external: true,
  },
  {
    id: 'appointment-setting-sop',
    title: 'Appointment Setting SOP',
    description: 'Procedures for setting appointments on behalf of members',
    url: 'https://netorg6712533-my.sharepoint.com/:w:/g/personal/julia_mympb_com/EW6RPk9jIJVOjH53SHbMzYcBAaPYxMsUW6VW5tRlyZDmyQ',
    category: 'internal-sops',
    type: 'sop',
    external: true,
  },
];
